/**
 * How the impact numbers are calculated.
 *
 * Every factor, its assumption and its source, listed in full. A climate
 * publication that shows people numbers owes them the working — and being able
 * to point here is what lets the rest of the app say "about 9 kg" without
 * hand-waving.
 */

import { Text } from '@/components/text';
import { gutter, hairline, spacing, useTheme } from '@/theme';
import { IMPACT_FACTORS } from '@climatenote/shared';
import { Linking, ScrollView, StyleSheet, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

export default function MethodologyScreen() {
  const { colors } = useTheme();
  const insets = useSafeAreaInsets();

  return (
    <ScrollView
      style={{ backgroundColor: colors.background }}
      contentContainerStyle={{
        paddingTop: insets.top + spacing.xl,
        paddingBottom: insets.bottom + spacing.giant,
        paddingHorizontal: gutter.article,
      }}
    >
      <Text variant="articleTitle" serif>
        How we calculate impact
      </Text>

      <Text variant="articleBody" serif style={styles.intro}>
        Every number in this app comes from a published average, listed below
        with its source. None of them are generated by AI.
      </Text>

      <Text variant="articleBody" serif style={styles.intro}>
        They are estimates, not measurements. What a beef meal actually costs
        depends on where the cattle were raised and how far the meat travelled;
        what a kilowatt-hour costs depends on what your local grid is burning
        tonight. Where a figure could plausibly be half or double what we show,
        we say so.
      </Text>

      <Text variant="articleBody" serif style={styles.intro}>
        When you write your own note and we cannot confidently match it to one
        of these, we log the action without a number rather than inventing one.
      </Text>

      {IMPACT_FACTORS.filter((factor) => factor.kgCo2ePerUnit > 0).map((factor) => (
        <View key={factor.key} style={[styles.entry, { borderTopColor: colors.border }]}>
          <Text variant="headline" serif={false}>
            {factor.label}
          </Text>

          <Text variant="subheadline" tone="brand" serif={false}>
            {factor.kgCo2ePerUnit} kg CO₂e per {factor.unit}
            {factor.uncertainty >= 2 ? ' (roughly)' : ''}
          </Text>

          <Text variant="footnote" tone="secondary" serif={false}>
            {factor.assumption}
          </Text>

          {factor.gridDependent ? (
            <Text variant="caption" tone="tertiary" serif={false}>
              Depends heavily on your local electricity mix.
            </Text>
          ) : null}

          <Text
            variant="caption"
            tone="brand"
            serif={false}
            onPress={() => void Linking.openURL(factor.sourceUrl)}
            accessibilityRole="link"
          >
            Source: {factor.sourceName}
          </Text>
        </View>
      ))}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  intro: { marginTop: spacing.lg },
  entry: { borderTopWidth: hairline, paddingTop: spacing.lg, marginTop: spacing.xl, gap: spacing.xs },
});
