-- ============================================================================
-- Impact factor seed.
--
-- GENERATED FILE — do not edit by hand.
-- Source: packages/shared/src/impact/factors.ts
-- Regenerate: pnpm --filter @climatenote/shared gen:factor-seed
--
-- Every figure the app shows a reader traces back to a row here, with its
-- assumption and source recorded alongside it.
-- ============================================================================

insert into impact_factors (
  key, label, category, unit, assumption,
  kg_co2e_per_unit, litres_water_per_unit, kg_waste_per_unit,
  uncertainty, grid_dependent, source_name, source_url
) values
  ('meal.beef_to_plant', 'Swapped a beef meal for a plant-based one', 'food', 'meal',
   'One meal containing about 100 g of beef, replaced by beans, lentils or tofu.',
   9.8, 1540, null,
   1.6, false, 'Poore & Nemecek (2018), Science — via Our World in Data', 'https://ourworldindata.org/environmental-impacts-of-food'),
  ('meal.lamb_to_plant', 'Swapped a lamb meal for a plant-based one', 'food', 'meal',
   'One meal containing about 100 g of lamb.',
   3.8, null, null,
   1.6, false, 'Poore & Nemecek (2018), Science — via Our World in Data', 'https://ourworldindata.org/environmental-impacts-of-food'),
  ('meal.cheese_to_plant', 'Swapped a cheese-heavy meal for a plant-based one', 'food', 'meal',
   'One meal containing about 80 g of cheese.',
   1.8, null, null,
   1.7, false, 'Poore & Nemecek (2018), Science — via Our World in Data', 'https://ourworldindata.org/environmental-impacts-of-food'),
  ('meal.chicken_to_plant', 'Swapped a chicken meal for a plant-based one', 'food', 'meal',
   'One meal containing about 120 g of chicken.',
   1, null, null,
   1.6, false, 'Poore & Nemecek (2018), Science — via Our World in Data', 'https://ourworldindata.org/environmental-impacts-of-food'),
  ('meal.meat_free_day', 'Ate no meat for a day', 'food', 'day',
   'A typical mixed-diet day, with all meat replaced by plant protein.',
   3.4, null, null,
   1.8, false, 'Poore & Nemecek (2018), Science — via Our World in Data', 'https://ourworldindata.org/environmental-impacts-of-food'),
  ('food.waste_avoided', 'Ate leftovers instead of throwing food away', 'food', 'kg of food',
   'Mixed household food, counting both production and landfill methane.',
   2.5, null, 1,
   2, false, 'US EPA WARM model / FAO food wastage footprint', 'https://www.epa.gov/warm'),
  ('food.dairy_milk_to_plant', 'Chose a plant milk over dairy', 'food', 'litre',
   'One litre of dairy milk replaced with oat or soy milk.',
   2.3, 550, null,
   1.5, false, 'Poore & Nemecek (2018), Science — via Our World in Data', 'https://ourworldindata.org/environmental-impacts-of-food'),
  ('transport.car_trip_avoided', 'Walked, cycled or skipped a car trip', 'transport', 'km',
   'An average petrol or diesel car, carrying one person.',
   0.17, null, null,
   1.4, false, 'UK DEFRA/DESNZ greenhouse gas conversion factors', 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting'),
  ('transport.car_to_bus', 'Took the bus instead of a car', 'transport', 'km',
   'Difference between a single-occupancy car and an average local bus.',
   0.07, null, null,
   1.5, false, 'UK DEFRA/DESNZ greenhouse gas conversion factors', 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting'),
  ('transport.car_to_train', 'Took the train instead of a car', 'transport', 'km',
   'Difference between a single-occupancy car and an average national rail journey.',
   0.13, null, null,
   1.5, false, 'UK DEFRA/DESNZ greenhouse gas conversion factors', 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting'),
  ('transport.carpooled', 'Shared a ride instead of travelling alone', 'transport', 'km',
   'One car trip shared with one other person, halving each share.',
   0.085, null, null,
   1.4, false, 'UK DEFRA/DESNZ greenhouse gas conversion factors', 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting'),
  ('energy.electricity_saved', 'Used less electricity', 'energy', 'kWh',
   'Average US grid mix. Much lower on a clean grid, much higher on a coal-heavy one.',
   0.37, null, null,
   2.2, true, 'US EPA eGRID, national average', 'https://www.epa.gov/egrid'),
  ('energy.laundry_cold_wash', 'Washed clothes on cold instead of hot', 'energy', 'load',
   'One machine load switched from a 40-60C cycle to cold.',
   0.6, null, null,
   1.8, true, 'US EPA / Energy Saving Trust appliance figures', 'https://www.energysavingtrust.org.uk/'),
  ('energy.air_dried_laundry', 'Air-dried laundry instead of tumble drying', 'energy', 'load',
   'One full tumble-dryer cycle avoided.',
   1.4, null, null,
   1.8, true, 'US EPA / Energy Saving Trust appliance figures', 'https://www.energysavingtrust.org.uk/'),
  ('energy.shorter_shower', 'Took a shorter shower', 'energy', 'minute',
   'One minute less under a 9 L/min showerhead with electric water heating.',
   0.19, 9, null,
   2, true, 'US EPA WaterSense / Energy Saving Trust', 'https://www.epa.gov/watersense'),
  ('energy.heating_turned_down', 'Turned the heating down a degree', 'energy', 'day',
   'One degree Celsius lower for a day in a typical heated home during the heating season.',
   0.9, null, null,
   2.5, false, 'Energy Saving Trust home heating figures', 'https://www.energysavingtrust.org.uk/'),
  ('waste.reusable_bottle', 'Used a reusable bottle instead of buying a plastic one', 'waste', 'bottle',
   'One 500 ml single-use PET bottle avoided, including production and disposal.',
   0.08, null, 0.02,
   1.6, false, 'US EPA WARM model', 'https://www.epa.gov/warm'),
  ('waste.reusable_cup', 'Brought a reusable cup', 'waste', 'cup',
   'One disposable coffee cup and lid avoided.',
   0.05, null, 0.015,
   1.8, false, 'US EPA WARM model', 'https://www.epa.gov/warm'),
  ('waste.recycled_can', 'Recycled an aluminium can', 'waste', 'can',
   'One can recycled rather than landfilled, counting avoided primary smelting.',
   0.09, null, 0.015,
   1.5, false, 'US EPA WARM model', 'https://www.epa.gov/warm'),
  ('waste.declined_single_use_plastic', 'Turned down single-use plastic', 'waste', 'item',
   'One small plastic item — bag, straw, cutlery, wrapper.',
   0.03, null, 0.008,
   2, false, 'US EPA WARM model', 'https://www.epa.gov/warm'),
  ('consumption.secondhand_clothing', 'Bought secondhand instead of new', 'consumption', 'garment',
   'One cotton t-shirt-equivalent garment, counting the new one not manufactured.',
   2.1, 2700, null,
   2, false, 'Ellen MacArthur Foundation / WRAP textiles data', 'https://wrap.org.uk/taking-action/textiles'),
  ('consumption.repaired_instead_of_replaced', 'Repaired something instead of replacing it', 'consumption', 'item',
   'A small household or electronic item kept in use for another year.',
   5, null, null,
   3, false, 'WRAP product lifetime research', 'https://wrap.org.uk/'),
  ('engagement.not_quantified', 'Took action (not measured in carbon)', 'consumption', 'action',
   'Learning, talking to someone, writing to a representative, joining a group. Real effects that carbon maths cannot honestly capture, so we log them and show no number.',
   0, null, null,
   1, false, 'Not applicable', '')
on conflict (key) do update set
  label                 = excluded.label,
  category              = excluded.category,
  unit                  = excluded.unit,
  assumption            = excluded.assumption,
  kg_co2e_per_unit      = excluded.kg_co2e_per_unit,
  litres_water_per_unit = excluded.litres_water_per_unit,
  kg_waste_per_unit     = excluded.kg_waste_per_unit,
  uncertainty           = excluded.uncertainty,
  grid_dependent        = excluded.grid_dependent,
  source_name           = excluded.source_name,
  source_url            = excluded.source_url;
